# Site settings
author: Joe Sanchez
title: Approaching my Mod 1 Final Project
header-img: img/home-bg.png
email: joe.987352@gmail.com
copyright_name: Joe Sanchez
description: > # this means to ignore newlines until "baseurl:"
  The first of many blogs for data science
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ayeejoeey

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
